//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
