//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Program = new HashSet<Student_Program>();
            this.Student_Schedule = new HashSet<Student_Schedule>();
        }
    
        public int id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string email { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string home_phone { get; set; }
        public string bussiness_phone { get; set; }
        public string mobile_phone { get; set; }
        public string fax_number { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string ZIP { get; set; }
        public string country { get; set; }
        public string company { get; set; }
        public string credit_trans { get; set; }
        public string refered { get; set; }
        public string web_page { get; set; }
        public string notes { get; set; }
        public string attachment { get; set; }
        public string location { get; set; }
        public string locker { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public string EO { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_phone1 { get; set; }
        public string emergency_contact_phone2 { get; set; }
        public string emergency_contact_phone3 { get; set; }
        
        //--- generated ----
        public string Full_Name
        {
            get
            {
                return first_name + " " + last_name;
            }
        }
        public virtual ICollection<Student_Program> Student_Program { get; set; }
        public virtual ICollection<Student_Schedule> Student_Schedule { get; set; }
    }
}
