//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 30/08/2014 15:48:29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace roster_visual
{

    /// <summary>
    /// VIEW
    /// </summary>
    [Table(Name = @"roster_mysql.studentview")]
    public partial class Studentview
    {
        #pragma warning disable 0649

        private int _ScheduleId;

        private string _Fullname;

        private string _Cv;

        private string _Picture;

        private string _ProgramScheduleName;

        private string _ProgramScheduleSlug;

        private string _Languages;

        private int _Id;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnScheduleIdChanging(int value);
        partial void OnScheduleIdChanged();
        partial void OnFullnameChanging(string value);
        partial void OnFullnameChanged();
        partial void OnCvChanging(string value);
        partial void OnCvChanged();
        partial void OnPictureChanging(string value);
        partial void OnPictureChanged();
        partial void OnProgramScheduleNameChanging(string value);
        partial void OnProgramScheduleNameChanged();
        partial void OnProgramScheduleSlugChanging(string value);
        partial void OnProgramScheduleSlugChanged();
        partial void OnLanguagesChanging(string value);
        partial void OnLanguagesChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        #endregion

        public Studentview()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ScheduleId in the schema.
        /// </summary>
        [Column(Name = @"schedule_id", Storage = "_ScheduleId", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int ScheduleId
        {
            get
            {
                return this._ScheduleId;
            }
            set
            {
                if (this._ScheduleId != value)
                {
                    this._ScheduleId = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Fullname in the schema.
        /// </summary>
        [Column(Name = @"fullname", Storage = "_Fullname", DbType = "MEDIUMTEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Fullname
        {
            get
            {
                return this._Fullname;
            }
            set
            {
                if (this._Fullname != value)
                {
                    this._Fullname = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Cv in the schema.
        /// </summary>
        [Column(Name = @"cv", Storage = "_Cv", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Cv
        {
            get
            {
                return this._Cv;
            }
            set
            {
                if (this._Cv != value)
                {
                    this._Cv = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Picture in the schema.
        /// </summary>
        [Column(Name = @"picture", Storage = "_Picture", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Picture
        {
            get
            {
                return this._Picture;
            }
            set
            {
                if (this._Picture != value)
                {
                    this._Picture = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramScheduleName in the schema.
        /// </summary>
        [Column(Name = @"program_schedule_name", Storage = "_ProgramScheduleName", CanBeNull = false, DbType = "MEDIUMTEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProgramScheduleName
        {
            get
            {
                return this._ProgramScheduleName;
            }
            set
            {
                if (this._ProgramScheduleName != value)
                {
                    this._ProgramScheduleName = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramScheduleSlug in the schema.
        /// </summary>
        [Column(Name = @"program_schedule_slug", Storage = "_ProgramScheduleSlug", DbType = "MEDIUMTEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProgramScheduleSlug
        {
            get
            {
                return this._ProgramScheduleSlug;
            }
            set
            {
                if (this._ProgramScheduleSlug != value)
                {
                    this._ProgramScheduleSlug = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Languages in the schema.
        /// </summary>
        [Column(Name = @"languages", Storage = "_Languages", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Languages
        {
            get
            {
                return this._Languages;
            }
            set
            {
                if (this._Languages != value)
                {
                    this._Languages = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this._Id = value;
                }
            }
        }
    }

}
